# Generated by Django 5.1.4 on 2025-05-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='course_images/')),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('student_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('lessons', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
                ('duration_months', models.PositiveIntegerField(blank=True, help_text='Duration in months', null=True)),
                ('total_classes', models.PositiveIntegerField(blank=True, null=True)),
                ('coaching_details', models.TextField(blank=True, null=True)),
                ('course_brochure', models.FileField(blank=True, null=True, upload_to='course_brochures/')),
                ('course_video', models.FileField(blank=True, null=True, upload_to='course_videos/')),
            ],
        ),
    ]
