# Generated by Django 5.1.4 on 2025-05-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0002_coursemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='certification',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('course_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='meta_app.coursemodel')),
            ],
        ),
    ]
