# Generated by Django 5.1.4 on 2025-05-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0003_coursemodel_certification_coursefaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_pdf',
        ),
    ]
